name: deploy

on:
  push:
    branches: [ master, staging ]

jobs:
  trigger-deploy:
    name: Trigger master deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dependent repositories
        env:
          GH_USERNAME: ${{ secrets.PAT_USERNAME }}
          GH_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -LO --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/trigger-gh-actions.sh
          sh trigger-gh-actions.sh ISO-TC211 schemas.isotc211.org $GH_USERNAME $GH_ACCESS_TOKEN deploy_${GITHUB_REF##*/}